In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Mumbai House Prices.csv")

In [3]:
df.head()

,bhk,type,locality,area,price,price_unit,region,status,age
0,3,Apartment,Lak And Hanware The Residency Tower,685,2.50,Cr,Andheri West,Ready to move,New
1,2,Apartment,Radheya Sai Enclave Building No 2,640,52.51,L,Naigaon East,Under Construction,New
2,2,Apartment,Romell Serene,610,1.73,Cr,Borivali West,Under Construction,New
3,2,Apartment,Soundlines Codename Urban Rainforest,876,59.98,L,Panvel,Under Construction,New
4,2,Apartment,Origin Oriana,659,94.11,L,Mira Road East,Under Construction,New

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76038 entries, 0 to 76037
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bhk         76038 non-null  int64
 1   type        76038 non-null  object
 2   locality    76038 non-null  object
 3   area        76038 non-null  int64
 4   price       76038 non-null  float64
 5   price_unit  76038 non-null  object
 6   region      76038 non-null  object
 7   status      76038 non-null  object
 8   age         76038 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 5.2+ MB

In [5]:
df.isnull().sum()

bhk           0
type          0
locality      0
area          0
price         0
price_unit    0
region        0
status        0
age           0
dtype: int64

In [6]:
df['type'].value_counts()

type
Apartment            74854
Studio Apartment       882
Villa                  226
Independent House       73
Penthouse                3
Name: count, dtype: int64

In [7]:
df['type'] = df['type'].replace(['Independent House','Penthouse'],'other')

In [8]:
df = pd.get_dummies(df,columns=['type'],drop_first=True)

In [9]:
df.head()

,bhk,locality,area,price,price_unit,region,status,age,type_Studio Apartment,type_Villa,type_other
0,3,Lak And Hanware The Residency Tower,685,2.50,Cr,Andheri West,Ready to move,New,False,False,False
1,2,Radheya Sai Enclave Building No 2,640,52.51,L,Naigaon East,Under Construction,New,False,False,False
2,2,Romell Serene,610,1.73,Cr,Borivali West,Under Construction,New,False,False,False
3,2,Soundlines Codename Urban Rainforest,876,59.98,L,Panvel,Under Construction,New,False,False,False
4,2,Origin Oriana,659,94.11,L,Mira Road East,Under Construction,New,False,False,False

In [10]:
df['locality'].value_counts()

locality
Hiranandani Meadows         861
Sheth Avalon                516
T Bhimjyani The Verraton    499
ACME Ozone Phase 2          467
Runwal Gardens              389
                           ...
Cosmos Angel Tower            1
Sheth Konark Empress          1
Shree Chamunda Garden         1
Vega Platinum Enclave         1
Omkar Puram                   1
Name: count, Length: 9782, dtype: int64

In [11]:
top_localities = df['locality'].value_counts().nlargest(20).index
df['locality'] = df['locality'].where(df['locality'].isin(top_localities),'other')

In [12]:
df = pd.get_dummies(df,columns=['locality'],drop_first=True)

In [13]:
df['area'].value_counts()

area
650     1662
1050    1381
1100    1151
1650    1041
750      950
        ...
2875       1
1987       1
1749       1
2793       1
2772       1
Name: count, Length: 2331, dtype: int64

In [14]:
df['area'].describe()

count    76038.000000
mean      1024.536850
std        670.276165
min        127.000000
25%        640.000000
50%        872.000000
75%       1179.000000
max      16000.000000
Name: area, dtype: float64

In [15]:
df['price'].value_counts()

price
1.75     972
1.25     948
1.35     854
1.15     846
1.10     839
        ...
45.08      1
60.36      1
58.32      1
48.02      1
60.55      1
Name: count, Length: 4729, dtype: int64

In [16]:
df['price'] = df.apply(lambda x:x['price']*100 if x['price_unit'] == 'Cr'else x['price'],axis=1)

In [17]:
df.head()

,bhk,area,price,price_unit,region,status,age,type_Studio Apartment,type_Villa,type_other,...,locality_Raj Akshay,locality_Reputed Builder Wild Wood Park 2,locality_Runwal Bliss,locality_Runwal Garden City Dahlia,locality_Runwal Gardens,locality_Sheth Avalon,locality_T Bhimjyani The Verraton,locality_Umiya Oasis,locality_Vasant Vasant Vihar,locality_other
0,3,685,250.00,Cr,Andheri West,Ready to move,New,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2,640,52.51,L,Naigaon East,Under Construction,New,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,2,610,173.00,Cr,Borivali West,Under Construction,New,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,2,876,59.98,L,Panvel,Under Construction,New,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,2,659,94.11,L,Mira Road East,Under Construction,New,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [18]:
df.drop(columns='price_unit',inplace=True)

In [19]:
df.head()

,bhk,area,price,region,status,age,type_Studio Apartment,type_Villa,type_other,locality_Amar Vinay Heritage,...,locality_Raj Akshay,locality_Reputed Builder Wild Wood Park 2,locality_Runwal Bliss,locality_Runwal Garden City Dahlia,locality_Runwal Gardens,locality_Sheth Avalon,locality_T Bhimjyani The Verraton,locality_Umiya Oasis,locality_Vasant Vasant Vihar,locality_other
0,3,685,250.00,Andheri West,Ready to move,New,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2,640,52.51,Naigaon East,Under Construction,New,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,2,610,173.00,Borivali West,Under Construction,New,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,2,876,59.98,Panvel,Under Construction,New,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,2,659,94.11,Mira Road East,Under Construction,New,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [20]:
df['region'].value_counts()

region
Thane West             14868
Mira Road East          9902
Dombivali               3041
Kandivali East          2568
Kharghar                2362
                       ...
Adaigaon                   1
Sector-4 New Panvel        1
Versova                    1
Sector 6 Kamothe           1
Pen                        1
Name: count, Length: 228, dtype: int64

In [21]:
top_region = df['region'].value_counts().nlargest(20).index
df['region'] = df['region'].where(df['region'].isin(top_region),'other')

In [22]:
df = pd.get_dummies(df,columns=['region'],drop_first=True)

In [23]:
df.head()

,bhk,area,price,status,age,type_Studio Apartment,type_Villa,type_other,locality_Amar Vinay Heritage,locality_Cosmos Horizon,...,region_Malad West,region_Mira Road East,region_Mulund West,region_Panvel,region_Powai,region_Thane West,region_Ulwe,region_Vikhroli,region_Virar,region_other
0,3,685,250.00,Ready to move,New,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,640,52.51,Under Construction,New,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,2,610,173.00,Under Construction,New,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,2,876,59.98,Under Construction,New,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,2,659,94.11,Under Construction,New,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [24]:
df['status'].value_counts()

status
Ready to move         44982
Under Construction    31056
Name: count, dtype: int64

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['status'] = le.fit_transform(df['status'])

In [26]:
df.head()

,bhk,area,price,status,age,type_Studio Apartment,type_Villa,type_other,locality_Amar Vinay Heritage,locality_Cosmos Horizon,...,region_Malad West,region_Mira Road East,region_Mulund West,region_Panvel,region_Powai,region_Thane West,region_Ulwe,region_Vikhroli,region_Virar,region_other
0,3,685,250.00,0,New,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,640,52.51,1,New,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,2,610,173.00,1,New,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,2,876,59.98,1,New,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,2,659,94.11,1,New,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [27]:
df['age'].value_counts()

age
New        38072
Resale     23357
Unknown    14609
Name: count, dtype: int64

In [28]:
df = pd.get_dummies(df,columns=['age'],drop_first=True)

In [29]:
df.head()

,bhk,area,price,status,type_Studio Apartment,type_Villa,type_other,locality_Amar Vinay Heritage,locality_Cosmos Horizon,locality_Hiranandani Estate,...,region_Mulund West,region_Panvel,region_Powai,region_Thane West,region_Ulwe,region_Vikhroli,region_Virar,region_other,age_Resale,age_Unknown
0,3,685,250.00,0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,640,52.51,1,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,2,610,173.00,1,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,2,876,59.98,1,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,2,659,94.11,1,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [30]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['area'] = scaler.fit_transform(df[['area']])

In [31]:
df.head()

,bhk,area,price,status,type_Studio Apartment,type_Villa,type_other,locality_Amar Vinay Heritage,locality_Cosmos Horizon,locality_Hiranandani Estate,...,region_Mulund West,region_Panvel,region_Powai,region_Thane West,region_Ulwe,region_Vikhroli,region_Virar,region_other,age_Resale,age_Unknown
0,3,0.035154,250.00,0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,0.032319,52.51,1,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,2,0.030429,173.00,1,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,2,0.047187,59.98,1,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,2,0.033516,94.11,1,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [32]:
df.to_csv("cleaned_data.csv",index=None)